project:
  type: website
  output-dir: .
  resources:
    - scripts.js
    - includes/scripts.html

website:
  title: "Michelle Marie Ricart â€” MBA Portfolio"
  navbar:
    logo: headshot.jpg
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills & Certifications
      - href: contact.qmd
        text: Contact
    right:
      - text: Reflection
        href: reflection.qmd
      - text: Appendix
        href: appendix.qmd
  reader-mode: true

format:
  html:
    theme: litera
    css: styles.scss
    toc: true
    smooth-scroll: true
    anchor-sections: true
    embed-resources: true
    include-after-body: includes.html  

